name: ci

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  stan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env
      - run: composer install
      - run: composer stan

  buildui:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env
      - run: composer install
      - run: composer run buildui

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose build
      - run: docker compose up -d --wait
      - run: docker compose exec app composer test
